# Generated by Django 4.2.7 on 2023-11-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CatID', models.BigAutoField(primary_key=True, serialize=False)),
                ('CatName', models.CharField(max_length=50)),
                ('CatDescription', models.TextField(blank=True)),
            ],
        ),
    ]
