# Generated by Django 4.2.7 on 2023-11-27 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bodega', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailArticle',
            fields=[
                ('DetArticleID', models.BigAutoField(primary_key=True, serialize=False)),
                ('DetArticleSerialNumber', models.CharField(max_length=50)),
                ('DetArticleStatusCondition', models.CharField(choices=[('Buen estado', 'Buen estado'), ('Defectuoso', 'Defectuoso'), ('Defectuoso de Fabrica', 'Defectuoso de Fabrica')], max_length=25)),
                ('DetArticleState', models.CharField(choices=[('Disponible', 'Disponible'), ('Prestado', 'Prestado'), ('No Disponible', 'No Disponible')], max_length=15)),
                ('DetArticleCreated', models.DateField(auto_now_add=True)),
                ('DetArticleUpdated', models.DateField(auto_now=True)),
                ('DetArticleComments', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('LoanID', models.BigAutoField(primary_key=True, serialize=False)),
                ('LoanStatus', models.CharField(choices=[('Activo', 'Activo'), ('Terminado', 'Terminado')], max_length=20)),
                ('LoanDescription', models.TextField()),
                ('LoanDateIn', models.DateField(auto_now_add=True)),
                ('LoanDateOut', models.DateField()),
                ('LoanDetArticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bodega.detailarticle')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralArticle',
            fields=[
                ('GenArticleID', models.BigAutoField(primary_key=True, serialize=False)),
                ('GenArticleName', models.CharField(max_length=50)),
                ('GenArticleModel', models.CharField(max_length=50)),
                ('GenArticlePartNumber', models.CharField(max_length=75)),
                ('GenArticleCat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bodega.category')),
            ],
        ),
        migrations.AddField(
            model_name='detailarticle',
            name='GeneralArticleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bodega.generalarticle'),
        ),
    ]
