# Generated by Django 4.2.7 on 2023-11-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bodega', '0002_detailarticle_loan_generalarticle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='LoanDateOut',
            field=models.DateField(blank=True),
        ),
    ]
