# Generated by Django 4.2.7 on 2023-11-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bodega', '0003_alter_loan_loandateout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='LoanDateOut',
            field=models.DateField(blank=True, null=True),
        ),
    ]
