# Generated by Django 4.2.7 on 2023-11-27 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bodega', '0004_alter_loan_loandateout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='LoanDetArticle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Bodega.detailarticle'),
        ),
    ]
